////////


#cmakedefine01 INCLUDE__ARDUINOCORE_API

#if (INCLUDE__ARDUINOCORE_API == 1)

#cmakedefine01 ARDUINOCORE_API__INCLUDE_TENSORFLOWLITE

#endif /* (INCLUDE__ARDUINOCORE_API == 1) */

